app:
  max_parallel_tasks_cnt: {{'max_parallel_tasks_cnt'|getenv('1')}}

read:
  root_pages:
      - page: <some page>
        space: <some space>

confluence:
  url: {{'confluence_url'|getenv('')}}
  auth_user: {{'confluence_auth_user'|getenv('')}}
  auth_password: {{'confluence_auth_password'|getenv('')}}
  auth_token: {{'confluence_publish_token'|getenv('')}}
  timeout_secs: 20
  retries_max: 3
  retries_delay_secs: 10
  retries_codes:
    - 403
    - 500
    - 400
#    - 409
  transaction_retries_max: 3
  transaction_retries_delay_secs: 10

logging:
  level: {{'logging_level'|getenv('INFO')}}